from typing import Literal

from pydantic import HttpUrl

from romanian_news.feeds.models import FeedRegistry, FeedSpec, registry_version_id


def feed_registry() -> FeedRegistry:
    """Return the versioned registry of live, first-party Romanian feeds."""
    feeds = tuple(sorted(_FEEDS, key=lambda feed: feed.id))
    return FeedRegistry(feeds=feeds, version_id=registry_version_id(feeds))


def _feed(
    id: str,
    outlet_id: str,
    outlet_name: str,
    url: str,
    category: Literal["general", "economic", "political", "investigative", "regional"],
    *hosts: str,
    article_xpath: str | None = None,
    excluded_article_path_prefixes: tuple[str, ...] = (),
) -> FeedSpec:
    return FeedSpec(
        id=id,
        outlet_id=outlet_id,
        outlet_name=outlet_name,
        url=HttpUrl(url),
        category=category,
        article_hosts=hosts,
        article_xpath=article_xpath,
        excluded_article_path_prefixes=excluded_article_path_prefixes,
    )


_FEEDS = (
    _feed(
        "adevarul",
        "adevarul",
        "Adevărul",
        "https://adevarul.ro/rss/index",
        "general",
        "adevarul.ro",
    ),
    _feed(
        "bihoreanul",
        "bihoreanul",
        "Bihoreanul",
        "https://www.ebihoreanul.ro/rss_today",
        "regional",
        "ebihoreanul.ro",
        article_xpath="//div[contains(concat(' ', normalize-space(@class), ' '), ' entry-content ')]",
    ),
    _feed(
        "buletin-bucuresti",
        "buletin-bucuresti",
        "Buletin de București",
        "https://buletin.de/bucuresti/feed/",
        "regional",
        "buletin.de",
        article_xpath="//*[contains(concat(' ', normalize-space(@class), ' '), ' post_content ') and contains(concat(' ', normalize-space(@class), ' '), ' jl_content ')]",
    ),
    _feed(
        "bursa-capital",
        "bursa",
        "Bursa",
        "https://www.bursa.ro/piata-capital-bursa.xml",
        "economic",
        "bursa.ro",
    ),
    _feed(
        "bursa-titluri",
        "bursa",
        "Bursa",
        "https://www.bursa.ro/titluri-bursa.xml",
        "economic",
        "bursa.ro",
    ),
    _feed("cluj24", "cluj24", "Cluj24", "https://cluj24.ro/feed/", "regional", "cluj24.ro"),
    _feed(
        "context",
        "context",
        "Context.ro",
        "https://context.ro/feed/",
        "investigative",
        "context.ro",
    ),
    _feed(
        "curs-guvernare",
        "curs-guvernare",
        "Curs de Guvernare",
        "https://cursdeguvernare.ro/feed",
        "economic",
        "cursdeguvernare.ro",
    ),
    _feed(
        "dcnews",
        "dcnews",
        "DCNews",
        "https://www.dcnews.ro/rss",
        "general",
        "dcnews.ro",
    ),
    _feed(
        "digi24",
        "digi24",
        "Digi24",
        "https://www.digi24.ro/rss",
        "general",
        "digi24.ro",
        article_xpath="//*[@id='article-content']//article[contains(concat(' ', normalize-space(@class), ' '), ' article-story ')]//*[contains(concat(' ', normalize-space(@class), ' '), ' entry ')]",
    ),
    _feed(
        "economedia",
        "economedia",
        "Economedia",
        "https://economedia.ro/feed",
        "economic",
        "economedia.ro",
    ),
    _feed(
        "economica",
        "economica",
        "Economica.net",
        "https://www.economica.net/feed",
        "economic",
        "economica.net",
        article_xpath="//*[contains(concat(' ', normalize-space(@class), ' '), ' single__content-container ')]//*[contains(concat(' ', normalize-space(@class), ' '), ' single__content ')]",
    ),
    _feed(
        "financial-intelligence",
        "financial-intelligence",
        "Financial Intelligence",
        "https://financialintelligence.ro/feed/",
        "economic",
        "financialintelligence.ro",
    ),
    _feed(
        "g4media",
        "g4media",
        "G4Media",
        "https://www.g4media.ro/feed",
        "political",
        "g4media.ro",
        article_xpath="//*[contains(concat(' ', normalize-space(@class), ' '), ' single__text ')]",
    ),
    _feed(
        "gazeta-de-sud",
        "gazeta-de-sud",
        "Gazeta de Sud",
        "https://www.gds.ro/Local/feed/",
        "regional",
        "gds.ro",
        article_xpath="//div[contains(concat(' ', normalize-space(@class), ' '), ' entry-content ')]",
    ),
    _feed(
        "hotnews",
        "hotnews",
        "HotNews",
        "https://hotnews.ro/feed",
        "general",
        "hotnews.ro",
        article_xpath="//*[contains(concat(' ', normalize-space(@class), ' '), ' article-single-content ')]",
    ),
    _feed(
        "info-sud-est",
        "info-sud-est",
        "Info Sud-Est",
        "https://www.info-sud-est.ro/feed/",
        "regional",
        "info-sud-est.ro",
    ),
    _feed(
        "libertatea",
        "libertatea",
        "Libertatea",
        "https://www.libertatea.ro/feed",
        "general",
        "libertatea.ro",
        article_xpath="//*[@id='article-content']",
    ),
    _feed(
        "monitorul-botosani",
        "monitorul-botosani",
        "Monitorul de Botoșani",
        "https://www.monitorulbt.ro/category/prima-pagina/feed/",
        "regional",
        "monitorulbt.ro",
        article_xpath="//div[contains(concat(' ', normalize-space(@class), ' '), ' tdb_title ')]/parent::div[1]",
        excluded_article_path_prefixes=("/national/",),
    ),
    _feed(
        "news-ro",
        "news-ro",
        "News.ro",
        "https://www.news.ro/rss",
        "general",
        "news.ro",
    ),
    _feed(
        "newscenter",
        "newscenter",
        "NewsCenter.ro",
        "https://newscenter.ro/feed/",
        "investigative",
        "newscenter.ro",
        article_xpath="//article[contains(@class, 'type-post')]//div[contains(@class, 'entry-content')]",
    ),
    _feed(
        "observator-news",
        "observator-news",
        "Observator News",
        "https://observatornews.ro/rss",
        "general",
        "observatornews.ro",
    ),
    _feed(
        "observatorul-prahovean",
        "observatorul-prahovean",
        "Observatorul Prahovean",
        "https://www.observatorulph.ro/feed",
        "regional",
        "observatorulph.ro",
        excluded_article_path_prefixes=("/advertorial/", "/national/", "/international/"),
    ),
    _feed(
        "pressone",
        "pressone",
        "PressOne",
        "https://pressone.ro/api/rss",
        "investigative",
        "pressone.ro",
        article_xpath="//article",
    ),
    _feed(
        "profit",
        "profit",
        "Profit.ro",
        "https://www.profit.ro/rss",
        "economic",
        "profit.ro",
        article_xpath="//*[contains(concat(' ', normalize-space(@class), ' '), ' custom-content ')]//*[contains(concat(' ', normalize-space(@class), ' '), ' art-content ')]",
    ),
    _feed(
        "realitatea",
        "realitatea",
        "Realitatea.net",
        "https://www.realitatea.net/access/share/feeds/rss/homepage.xml",
        "general",
        "realitatea.net",
        article_xpath="(//article)[1]//div[contains(concat(' ', normalize-space(@class), ' '), ' prose ')][1]",
    ),
    _feed(
        "recorder",
        "recorder",
        "Recorder",
        "https://recorder.ro/feed/",
        "investigative",
        "recorder.ro",
        article_xpath="//article//*[contains(concat(' ', normalize-space(@class), ' '), ' single-content-content ')]",
    ),
    _feed(
        "rfi-romania",
        "rfi-romania",
        "RFI România",
        "https://www.rfi.fr/ro/rss",
        "general",
        "rfi.fr",
    ),
    _feed(
        "rfi-romania-economia-reala",
        "rfi-romania",
        "RFI România",
        "https://www.rfi.fr/ro/podcasturi/economia-real%C4%83/podcast",
        "economic",
        "rfi.fr",
    ),
    _feed(
        "rise-project",
        "rise-project",
        "RISE Project",
        "https://www.riseproject.ro/feed/",
        "investigative",
        "riseproject.ro",
    ),
    _feed(
        "romania-actualitati",
        "romania-actualitati",
        "Radio România Actualități",
        "https://www.romania-actualitati.ro/rss",
        "general",
        "romania-actualitati.ro",
    ),
    _feed(
        "romania-tv",
        "romania-tv",
        "România TV",
        "https://www.romaniatv.net/feed",
        "general",
        "romaniatv.net",
    ),
    _feed("snoop", "snoop", "Snoop", "https://snoop.ro/feed/", "investigative", "snoop.ro"),
    _feed(
        "special-arad",
        "special-arad",
        "Special Arad",
        "https://specialarad.ro/articole/stiri-arad/feed/",
        "regional",
        "specialarad.ro",
    ),
    _feed(
        "special-arad-investigatii",
        "special-arad",
        "Special Arad",
        "https://specialarad.ro/articole/investigatii/feed/",
        "regional",
        "specialarad.ro",
    ),
    _feed(
        "special-arad-reportaj",
        "special-arad",
        "Special Arad",
        "https://specialarad.ro/articole/reportaj/feed/",
        "regional",
        "specialarad.ro",
    ),
    _feed(
        "spotmedia",
        "spotmedia",
        "SpotMedia",
        "https://spotmedia.ro/feed",
        "political",
        "spotmedia.ro",
    ),
    _feed(
        "startupcafe",
        "startupcafe",
        "StartupCafe",
        "https://startupcafe.ro/feed",
        "economic",
        "startupcafe.ro",
    ),
    _feed(
        "stirile-protv",
        "stirile-protv",
        "Știrile ProTV",
        "https://stirileprotv.ro/rss/",
        "general",
        "stirileprotv.ro",
    ),
    _feed(
        "turnul-sfatului",
        "turnul-sfatului",
        "Turnul Sfatului",
        "https://www.turnulsfatului.ro/feed/",
        "regional",
        "turnulsfatului.ro",
    ),
    _feed(
        "wall-street",
        "wall-street",
        "Wall-Street.ro",
        "https://www.wall-street.ro/rssfeeds/index.xml",
        "economic",
        "wall-street.ro",
    ),
    _feed(
        "ziarul-financiar",
        "ziarul-financiar",
        "Ziarul Financiar",
        "https://www.zf.ro/rss/",
        "economic",
        "zf.ro",
        article_xpath="//*[contains(concat(' ', normalize-space(@class), ' '), ' article ')]//*[contains(concat(' ', normalize-space(@class), ' '), ' text-content ')]",
        excluded_article_path_prefixes=("/auxiliar/",),
    ),
)
